/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:b2d77bb333dc480e95fc07a3ff605f33:53c5af0e59e75dcb0b7e7175332caeca:c32b14f25b044fad7807043096746115$
 *
 */
namespace myGame
{
	public class Spritesheet
	{
		public const string Ball_down = "ball_down";
		public const string Ball_up = "ball_up";
		public const string Blank = "blank";
		public const string Checkpoint_flag1 = "checkpoint_flag1";
		public const string Checkpoint_flag2 = "checkpoint_flag2";
		public const string Checkpoint_flag3 = "checkpoint_flag3";
		public const string Checkpoint_flag4 = "checkpoint_flag4";
		public const string Coin = "coin";
		public const string Move_button = "move_button";
		public const string Play_button = "play_button";
		public const string Spike = "spike";
		public const string Spike_tile = "spike_tile";
		public const string Tile = "tile";
		public const string Win_flag1 = "win_flag1";
		public const string Win_flag2 = "win_flag2";
		public const string Win_flag3 = "win_flag3";
		public const string Win_flag4 = "win_flag4";
	}
}